### ISSUE TITLE
Issue with CIDER, the Clojure Interactive Development Environment for Emacs

### ISSUE THREAD

**Issue by ck** [venantius/ultra#13] opened 2015-02-02 16:45 UTC
It seems Ultra causes CIDER to report the following incompatibility:

    WARNING: The following required nREPL ops are not supported: 
    apropos classpath complete eldoc info inspect-start inspect-refresh inspect-pop inspect-push inspect-    reset macroexpand ns-list ns-vars resource stacktrace toggle-trace-var toggle-trace-ns undef
    Please, install (or update) cider-nrepl 0.9.0-SNAPSHOT and restart CIDER

See originally reported issue https://github.com/clojure-emacs/cider/issues/961

**Comment by venantius** [comment] 2015-02-02 17:50
Interesting. Forgive the naive question, but what nREPL client does this show up on? I've got CIDER-nrepl in my ~/.lein/profiles.clj and don't get the warning when initiating a repl with `lein repl`

**Comment by venantius** [comment] 2015-02-03 02:23
Another question, while I'm at it: would you mind disabling Ultra's features (https://github.com/venantius/ultra#configuration) to see which feature is triggering this? As I'm not an emacs user I don't have much native insight into what the root cause would be here, but that's probably the right way to start.

**Comment by ck** [comment] 2015-02-03 13:46
It seems to be a problem with the `:repl` option.

The following configuration

    {:repl        false
     :stacktraces true
     :tests       true
     :java        true}

starts CIDER without warnings:

    ; CIDER 0.9.0snapshot (package: 20150201.1117) (Java 1.7.0_71, Clojure 1.6.0, nREPL 0.2.6)

In contrast, the following configuration

    {:repl        true
     :stacktraces false
     :tests       false
     :java        false}
     
creates a warning:
     
    WARNING: The following required nREPL ops are not supported: 
    apropos classpath complete eldoc info inspect-start inspect-refresh inspect-pop inspect-push inspect-reset macroexpand ns-list ns-vars     resource stacktrace toggle-trace-var toggle-trace-ns undef
    Please, install (or update) cider-nrepl 0.9.0-SNAPSHOT and restart CIDER

**Comment by venantius** [comment] 2015-02-22 03:08
I believe this should be fixed as of the latest release `0.2.1` 

Please update and let me know if you're still experiencing the problem.

**Closed by venantius** 2015-02-22 03:08 UTC
